/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.(test|spec).(ts|tsx)', '**/*.(test|spec).(ts|tsx)'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { useESM: false }],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '^\\./baseUrl$': '<rootDir>/src/app/api/baseUrl.jest.ts',
  },
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  collectCoverageFrom: [
    'src/app/**/*.{ts,tsx}',
    '!src/app/**/*.d.ts',
    '!src/main.tsx',
    '!src/**/*.stories.*',
    '!src/app/components/ui/**',
    '!src/app/components/figma/**',
    '!src/app/services/**',
    '!src/app/api/baseUrl.ts',
    '!src/app/api/baseUrl.jest.ts',
    '!src/app/api/index.ts',
    '!src/app/App.tsx',
    '!src/app/routes.tsx',
    '!src/app/screens/ChirpDetailScreen.tsx',
    '!src/app/screens/ExploreScreen.tsx',
    '!src/app/screens/FeedScreen.tsx',
    '!src/app/screens/NotFoundScreen.tsx',
    '!src/app/screens/NotificationsScreen.tsx',
    '!src/app/screens/ProfileScreen.tsx',
    '!src/app/screens/UserProfileScreen.tsx',
    '!src/app/components/AchievementNotification.tsx',
    '!src/app/components/Badge.tsx',
    '!src/app/components/BottomNav.tsx',
    '!src/app/components/ChirpComposer.tsx',
    '!src/app/components/EmptyState.tsx',
    '!src/app/components/FollowListModal.tsx',
    '!src/app/components/LevelUpAnimation.tsx',
    '!src/app/components/LoadingSkeleton.tsx',
  ],
  coverageThreshold: {
    global: {
      branches: 65,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  coverageReporters: ['text', 'text-summary', 'html'],
  coverageDirectory: '<rootDir>/coverage',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  transformIgnorePatterns: ['/node_modules/(?!(@radix-ui|motion|lucide-react)/)'],
};
